language: rust
os:
  - linux
  - osx
  - windows

rust:
  - stable

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup target add x86_64-pc-windows-msvc; fi

before_script:
  - export MSRV=1.36.0
  - rustup toolchain install nightly
  - rustup toolchain install $MSRV
  - rustup component add rustfmt
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export TARGET=--target=x86_64-pc-windows-msvc; fi
  - cargo install $TARGET cargo-expand

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export TARGET=--target=x86_64-pc-windows-msvc; fi
  - cargo +$MSRV build $TARGET --verbose --all
  - cargo +$MSRV test
  - cd test-project
  - cargo +$MSRV test -- --nocapture
  - cd ../test-procmacro-project
  - cargo +$MSRV test -- --nocapture
