[package]
name = "test_procmacro_project"
version = "0.1.0"
authors = ["eupn <eupn@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "2.0"

[dev-dependencies]
macrotest = { path = "../" }
